{
  flake.modules.nixos.teamspeak-server = { pkgs, lib, config, ... }: {
    # Auto-generated by compose2nix.
    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."teamspeak-server" = {
      image = "teamspeaksystems/teamspeak6-server:latest";
      environment = {
        "TSSERVER_DEFAULT_PORT" = "9987";
        "TSSERVER_FILE_TRANSFER_IP" = "0.0.0.0";
        "TSSERVER_FILE_TRANSFER_PORT" = "30033";
        "TSSERVER_QUERY_SSH_ENABLED" = "true";
        "TSSERVER_LICENSE_ACCEPTED" = "accept";
        "TSSERVER_VOICE_IP" = "0.0.0.0";
      };
      volumes = [
        "teamspeak-data:/var/tsserver:rw"
      ];
      ports = [
        "9987:9987/udp"
        "30033:30033/tcp"
        "127.0.0.1:10022:10022/tcp" # ssh query
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=teamspeak"
        "--network=teamspeak_default"
      ];
    };
    systemd.services."podman-teamspeak-server" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-teamspeak_default.service"
        "podman-volume-teamspeak-data.service"
      ];
      requires = [
        "podman-network-teamspeak_default.service"
        "podman-volume-teamspeak-data.service"
      ];
      partOf = [
        "podman-compose-teamspeak-root.target"
      ];
      wantedBy = [
        "podman-compose-teamspeak-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-teamspeak_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f teamspeak_default";
      };
      script = ''
        podman network inspect teamspeak_default || podman network create teamspeak_default
      '';
      partOf = [ "podman-compose-teamspeak-root.target" ];
      wantedBy = [ "podman-compose-teamspeak-root.target" ];
    };

    # Volumes
    systemd.services."podman-volume-teamspeak-data" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect teamspeak-data || podman volume create teamspeak-data
      '';
      partOf = [ "podman-compose-teamspeak-root.target" ];
      wantedBy = [ "podman-compose-teamspeak-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-teamspeak-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
