keys:
  - &max age1xp0sfs0cfrpr3ymufaz4hxu95c0r5nmy4ufuef22uw7v9mvtf4cszj3lmp
  - &host_dutch age1jpxp0vjmq3r28z32475kls8dt4nh2m7ee3ysvnvuzexglug4sgyq0zhya9
  - &host_bob age1kq42v4uxfjh2cf3xv86494t3r8htj72laefh8lfv6fndp2n8xutswx2f4t
  - &host_squid age1raequfgm7w4x08caenyknck68ax2d8s225meez9zlrvfkdn39ssqq2p3fs
creation_rules:
  - path_regex: hosts/dutch/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *max
          - *host_dutch
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *max
          - *host_bob
          - *host_squid
