#!/usr/bin/env bash
selection=$(find "$HOME"/.password-store -type f -name '*.gpg' -printf '%P\n' | sed 's/.gpg$//g' | sort | fuzzel --width 60 --dmenu)

if [ -n "$selection" ]; then
    pass show -c "$selection"
fi
