# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  sops.secrets."valheim.env" = { };
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."valheim-valheim" = {
    image = "ghcr.io/lloesche/valheim-server";
    environmentFiles = [
      config.sops.secrets."valheim.env".path
    ];
    environment = {
      "BACKUPS_MAX_AGE" = "30";
      "PGID" = "1000";
      "PUID" = "1000";
      "SERVER_PUBLIC" = "0";
      "TZ" = "Europe/Berlin";
      "WORLD_NAME" = "welt";
    };
    volumes = [
      "/var/lib/valheim-server/config:/config:rw"
      "/var/lib/valheim-server/data:/opt/valheim:rw"
    ];
    ports = [
      "2456:2456/udp"
      "2457:2457/udp"
      "2458:2458/udp"
      "9001:9001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=sys_nice"
      "--network-alias=valheim"
      "--network=valheim_default"
    ];
  };
  systemd.services."podman-valheim-valheim" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-valheim_default.service"
    ];
    requires = [
      "podman-network-valheim_default.service"
    ];
    partOf = [
      "podman-compose-valheim-root.target"
    ];
    wantedBy = [
      "podman-compose-valheim-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-valheim_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f valheim_default";
    };
    script = ''
      podman network inspect valheim_default || podman network create valheim_default
    '';
    partOf = [ "podman-compose-valheim-root.target" ];
    wantedBy = [ "podman-compose-valheim-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-valheim-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  networking.firewall.allowedTCPPorts = [ 9001 ];
  networking.firewall.allowedUDPPortRanges = [{
    from = 2456;
    to = 2458;
  }];
}
